/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utp.misiontic2022.c2.p23.reto4;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.JTable;

import utp.misiontic2022.c2.p23.reto4.modelo.vo.Requerimiento_1;
import utp.misiontic2022.c2.p23.reto4.modelo.vo.Requerimiento_2;
import utp.misiontic2022.c2.p23.reto4.modelo.vo.Requerimiento_3;
import utp.misiontic2022.c2.p23.reto4.vista.VistaRequerimientos;
import utp.misiontic2022.c2.p23.reto4.controlador.ControladorRequerimientos;
/**
 *
 * @author User
 */
public class interfaz extends JFrame {

    /**
     * Creates new form interfaz
     */
    public interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonConsulta1 = new javax.swing.JButton();
        botonConsulta2 = new javax.swing.JButton();
        botonConsulta3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Reto 5");

        jLabel2.setText("Conocer el id y la constructora de los proyectos de tipo 1 y acabados en ‘Si’");

        jLabel3.setText("Conocer el id y la constructora de los proyectos que tengan en su tipo el estrato 2");

        jLabel4.setText("Obtener el id y la fecha de los proyectos cuyo banco empiecen por la letra ‘B’ y la constructora empiece por la letra ‘H’");

        botonConsulta1.setText("Consulta 1");
        botonConsulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsulta1ActionPerformed(evt);
            }
        });

        botonConsulta2.setText("Consulta 2");
        botonConsulta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsulta2ActionPerformed(evt);
            }
        });

        botonConsulta3.setText("Consulta 3");
        botonConsulta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsulta3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(botonConsulta1)
                    .addComponent(botonConsulta2)
                    .addComponent(botonConsulta3))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(245, 245, 245))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(botonConsulta1)
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addComponent(botonConsulta2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(botonConsulta3)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonConsulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsulta1ActionPerformed        
        ArrayList<Requerimiento_1> resultado = VistaRequerimientos.requerimiento1();
        Object [][] matriz = new Object [resultado.size()][2];
        for(int i=0; i < resultado.size();i++){
            matriz[i][0] = resultado.get(i).getID_Proyecto();
            matriz[i][1] = resultado.get(i).getConstructora();
        }
        Modelo modelo = new Modelo();
        modelo.datos = matriz;
        JTable tabla = new JTable(modelo);
        JScrollPane scroll = new JScrollPane(tabla);
        JOptionPane.showMessageDialog(null, scroll);
    }

    private void botonConsulta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsulta2ActionPerformed
        ArrayList<Requerimiento_2> resultado = VistaRequerimientos.requerimiento2();
        Object [][] matriz = new Object [resultado.size()][2];
        for(int i=0; i < resultado.size();i++){
            matriz[i][0] = resultado.get(i).getID_Proyecto();
            matriz[i][1] = resultado.get(i).getConstructora();
        }
        Modelo modelo = new Modelo();
        modelo.datos = matriz;
        JTable tabla = new JTable(modelo);
        JScrollPane scroll = new JScrollPane(tabla);
        JOptionPane.showMessageDialog(null, scroll);
    }//GEN-LAST:event_botonConsulta2ActionPerformed

    private void botonConsulta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsulta3ActionPerformed
        ArrayList<Requerimiento_3> resultado = VistaRequerimientos.requerimiento3();
        Object [][] matriz = new Object [resultado.size()][2];
        for(int i=0; i < resultado.size();i++){
            matriz[i][0] = resultado.get(i).getID_Proyecto();
            matriz[i][1] = resultado.get(i).getFecha_Inicio();
        }
        Modelo modelo = new Modelo();
        modelo.datos = matriz;
        JTable tabla = new JTable(modelo);
        JScrollPane scroll = new JScrollPane(tabla);
        JOptionPane.showMessageDialog(null, scroll);
    }//GEN-LAST:event_botonConsulta3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConsulta1;
    private javax.swing.JButton botonConsulta2;
    private javax.swing.JButton botonConsulta3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
